magician:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
    #pid: {p: 100.0, i: 0.01, d: 10.0}
    gains:
      joint_1:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  joint2_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - joint_2
    #pid: {p: 100.0, i: 0.01, d: 10.0}
    gains:
      joint_2:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  joint5_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - joint_5
    # pid: {p: 100.0, i: 0.01, d: 10.0}
    gains:
      joint_5:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  joint6_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - joint_6
    # pid: {p: 100.0, i: 0.01, d: 10.0}
    gains:
      joint_6:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  joint7_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - joint_7
    # pid: {p: 100.0, i: 0.01, d: 10.0}
    gains:
      joint_7:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}